CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity INTEGER NOT NULL,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    idempotency_key VARCHAR(255),
    notes VARCHAR(255),
    start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    version BIGINT,
    resource_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT uk_booking_resource_slot
        UNIQUE (resource_id, start_time, end_time),

    CONSTRAINT uk_bookings_idempotency_key
        UNIQUE (idempotency_key),

    CONSTRAINT bookings_status_check
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'CHECKED_IN',
                'COMPLETED',
                'CANCELLED',
                'NO_SHOW'
            )
        ),

    CONSTRAINT fk_bookings_resource
        FOREIGN KEY (resource_id)
        REFERENCES resources(id),

    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);